-- =============================================================
-- Account Service - V1 Initial Migration (Phase 0 placeholder)
-- =============================================================
-- This script intentionally contains no DDL.
-- Flyway requires at least one migration file to be present;
-- this placeholder satisfies that requirement and establishes
-- the migration baseline at version 1.
--
-- Real schema will be created in:
--   V2__create_accounts_table.sql       (Phase 3)
-- =============================================================
