spring:
  datasource:
    url: ${CLICKHOUSE_LOCAL_URL:jdbc:ch://127.0.0.1:8123/default?http_connection_provider=HTTP_CLIENT}
    hikari:
      initializationFailTimeout: -1
      connection-test-query: SELECT 1
      connection-timeout: 30000
      validation-timeout: 5000
      maximum-pool-size: 5
      minimum-idle: 1
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cms
